### ISSUE TITLE
UnsatisfiedLinkError libjnidispatch.so

### ISSUE THREAD

**Issue by hegazy** [watson-developer-cloud/speech-android-sdk#14]
I got this error when starting speech to text module

```
           SpeechToText    recognize
                           ws connecting with Basic Authentication
audio.WebSocketUploader    New WebSocketUploader: wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=en-US_BroadbandModel
                           wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=en-US_BroadbandModel
                           Connecting...
     AudioCaptureThread    recording started!
         AndroidRuntime    FATAL EXCEPTION: initStreamToServerThread
                           Process: com.skios.elizatourism, PID: 22797
                           java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/android-arm/libjnidispatch.so) not found in resource path (.)
                               at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:786)
                               at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:746)
                               at com.sun.jna.Native.<clinit>(Native.java:135)
                               at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:82)
                               at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:337)
                               at com.ibm.watson.developer_cloud.android.speech_to_text.v1.opus.JNAOpus.<clinit>(JNAOpus.java:42)
                               at com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.OggOpusEnc.initEncoderWithUploader(OggOpusEnc.java:53)
                               at com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploader.initStreamAudioToServer(WebSocketUploader.java:113)
                               at com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploader.access$000(WebSocketUploader.java:46)
                               at com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploader$2.run(WebSocketUploader.java:175)

```

**Comment by hegazy** [comment]
I got the problem. it's because of using the cardboard SDK and it was shipping its shared objects as arm-v7a only and you're shipping yours as arm only. I don't know how to solve this yet but this ain't your problem.
