### ISSUE TITLE
crash when microphone permissions are not granted

### ISSUE THREAD

**Issue by nacho4d** [watson-developer-cloud/speech-android-sdk#26]
I got the following crash (in the simulator) when trying to use STT and microphone permissions were not granted. 

```
07-21 23:09:42.622 23782-23831/com.example.hello D/com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploader: wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=ja-JP_BroadbandModel
07-21 23:09:42.623 23782-24744/com.example.hello D/com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploader: Connecting...
07-21 23:09:42.626 1209-1601/? E/audio_hw_generic: Error opening input stream format 1, channel_mask 0010, sample_rate 16000
07-21 23:09:42.626 1209-1815/? W/ServiceManager: Permission failure: android.permission.RECORD_AUDIO from uid=10060 pid=23782

                                                 [ 07-21 23:09:42.626  1209: 1815 E/         ]
                                                 Request requires android.permission.RECORD_AUDIO
07-21 23:09:42.626 1209-1815/? E/AudioFlinger: openRecord() permission denied: recording not allowed
07-21 23:09:42.627 23782-24745/com.example.hello E/AudioRecord: AudioFlinger could not create record track, status: -1
07-21 23:09:42.627 1209-24747/? I/AudioFlinger: AudioFlinger's thread 0xb3c00000 ready to run
07-21 23:09:42.627 23782-24745/com.example.hello E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
07-21 23:09:42.627 23782-24745/com.example.hello E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
07-21 23:09:42.627 23782-24745/com.example.hello E/AudioCaptureThread: Error reading voice audio
                                                                       java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
                                                                           at android.media.AudioRecord.startRecording(AudioRecord.java:885)
                                                                           at com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.AudioCaptureThread.run(AudioCaptureThread.java:62)


                                                                       --------- beginning of crash
07-21 23:09:42.628 23782-24745/com.example.hello E/AndroidRuntime: FATAL EXCEPTION: Thread-224
                                                                   Process: com.example.hello, PID: 23782
                                                                   java.lang.IllegalStateException: stop() called on an uninitialized AudioRecord.
                                                                       at android.media.AudioRecord.stop(AudioRecord.java:928)
                                                                       at com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.AudioCaptureThread.run(AudioCaptureThread.java:92)


                                                                   --------- beginning of system
07-21 23:09:42.628 1535-2000/system_process W/ActivityManager:   Force finishing activity com.example.hello/com.ibm.jp.tmnf.watson.WatsonDialogAndSpeech.WatsonActivity
07-21 23:09:42.657 1535-1580/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
07-21 23:09:42.658 2176-24749/com.google.android.gms D/DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics.
07-21 23:09:43.131 1535-1549/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{dfc5505 u0 com.example.hello/com.ibm.jp.tmnf.watson.WatsonDialogAndSpeech.WatsonActivity t97 f}
07-21 23:09:43.341 23782-24750/com.example.hello D/com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploader: WS connection opened successfully
07-21 23:09:43.341 23782-24744/com.example.hello D/com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploader: Connected
07-21 23:09:43.345 23782-24744/com.example.hello D/com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploader: Sending init message: {"action":"start","content-type":"audio\/ogg;codecs=opus","interim_results":true,"continuous":true,"inactivity_timeout":300}
07-21 23:09:43.345 23782-24744/com.example.hello D/com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploader: WebSocket Connection established
07-21 23:09:43.626 23782-24750/com.example.hello D/com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploaderonMessage: {
                                                                                                                                                 "state": "listening"
                                                                                                                                              }
07-21 23:09:52.631 1535-1549/system_process W/ActivityManager: Launch timeout has expired, giving up wake lock!
07-21 23:10:06.626 1535-1546/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
07-21 23:10:06.630 1209-1815/? D/WVCdm: Instantiating CDM.
07-21 23:10:06.630 1209-1602/? I/WVCdm: CdmEngine::OpenSession
07-21 23:10:06.630 1209-1602/? I/WVCdm: Level3 Library Sep 28 2015 13:08:28
07-21 23:10:06.631 1209-1602/? W/WVCdm: Could not read /data/mediadrm/IDM1013/ay64.dat2: No such file or directory
07-21 23:10:06.631 1209-1602/? W/WVCdm: Could not load liboemcrypto.so. Falling back to L3.  dlopen failed: library "liboemcrypto.so" not found
07-21 23:10:06.634 1209-1602/? I/WVCdm: CdmEngine::QueryKeyControlInfo
07-21 23:10:06.634 1209-1209/? W/WVCdm: BufferReader::Read<T> : Failure during parse: Not enough bytes (4)
07-21 23:10:06.634 1209-1209/? W/WVCdm: CdmEngine::ExtractWidevinePssh: Unable to read atom size.
07-21 23:10:06.634 1209-1209/? I/WVCdm: CdmEngine::GenerateKeyRequest
07-21 23:10:06.635 1209-1209/? D/WVCdm: PrepareKeyRequest: nonce=1743666901
07-21 23:10:06.688 1209-1601/? I/WVCdm: CdmEngine::CloseSession
07-21 23:10:06.997 4711-4711/? W/Binder_2: type=1400 audit(0.0:10): avc: denied { read } for name="/" dev="tmpfs" ino=3073 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:device:s0 tclass=dir permissive=0
07-21 23:10:07.200 1868-25107/com.google.android.gms.persistent W/GLSUser: [AppCertManager] IOException while requesting key: 
                                                                           java.io.IOException: Invalid device key response.
                                                                               at exx.a(SourceFile:267)
                                                                               at exx.a(SourceFile:2235)
                                                                               at exw.a(SourceFile:46)
                                                                               at exq.a(SourceFile:55)
                                                                               at exp.a(SourceFile:113)
                                                                               at com.google.android.gms.auth.account.be.legacy.AuthCronChimeraService.a(SourceFile:1054)
                                                                               at ovi.run(SourceFile:179)
07-21 23:10:13.840 23782-24750/com.example.hello D/com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploaderonMessage: {
                                                                                                                                                 "error": "Session timed out due to inactivity after 30 seconds."
                                                                                                                                              }
07-21 23:10:13.840 23782-24750/com.example.hello D/WatsonJSInterface: No results found. {
                                                                         "error": "Session timed out due to inactivity after 30 seconds."
                                                                      }
07-21 23:10:13.843 23782-24750/com.example.hello D/com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploader: WebSocket closed
07-21 23:10:13.843 23782-24750/com.example.hello D/com.ibm.watson.developer_cloud.android.speech_to_text.v1.audio.WebSocketUploader: ### Code: 1011 reason: see the previous message for the error details. remote: true
07-21 23:10:13.843 23782-24750/com.example.hello D/WatsonJSInterface: onClose: code:1011 reason:see the previous message for the error details. remote:true
```

I solved the problem by going "Settings" -> "Apps" -> "MyApp" -> "Permissions" and toggling microphone to "ON" although it would be better if the app does not crash on such situation.

**Comment by mihui** [comment]
Didn't see this kind of settings, but I did updates 2 weeks ago according to this crash:
https://github.com/mihui/speech-android-sdk/commit/616449a5f54bc823a56e8b72036a858529c51052

**Comment by nacho4d** [comment]
@mihui Thanks for the hint!

**Comment by mihui** [comment]
Now pull request has been sent, please check if it can address this issue. Thanks.
