### ISSUE TITLE
documentation is awful mate...

### ISSUE THREAD

**Issue by AndreiD** [watson-developer-cloud/speech-android-sdk#31]
You really don't maintain this...  and you just make developers look for other solutions -> IBM loses money -> why should they pay you if you can't write some **basic** documentation ? ....

**Comment by AndreiD** [comment]
to make your job easier here's a list of what is not clear 

### ?!?!??!

JSONObject models = getModels(); 
this.getHost(STT_URL)  

There are also 9 issues opened by other developers... 🚓

**Comment by AndreiD** [comment]
R.string.modelDefault  ??

**Comment by AndreiD** [comment]
iIndexDefault = iItems; is not used. Don't keep unused code in the examples. It just creates more confusion and it's harder to read..

**Comment by AndreiD** [comment]
E/AndroidRuntime: FATAL EXCEPTION: Thread-834

```
                                                                           java.lang.RuntimeException: unkonow schemehttps
                                                                               at org.java_websocket.client.WebSocketClient.getPort(WebSocketClient.java:298)
                                                                               at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:219)
                                                                               at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:204)
                                                                               at java.lang.Thread.run(Thread.java:818)
```

I give up.....

**Comment by germanattanasio** [comment]
Hey @AndreiD take a look at the https://github.com/watson-developer-cloud/android-sdk It uses the https://github.com/watson-developer-cloud/java-sdk. 

This repository is being deprecated.

**Comment by AndreiD** [comment]
so you're telling me that I spent 30 min because someone is too lazy to write big on readme

take a look at the https://github.com/watson-developer-cloud/android-sdk It uses the https://github.com/watson-developer-cloud/java-sdk.

This repository is being deprecated.

????????????????

**Comment by germanattanasio** [comment]
Life is hard @AndreiD
